SAT trade component aggregated over time query
unepwcmc/SAPI pull request #862
Opened 2022-06-29 11:31 UTC by lucacug

## Changes

| Feat | add endpoint to retrieve aggregated over time data for the "Reported by" tab of the SAT trade component |

### Comments

For now, I have implemented this as a new endpoint, ideally, I could have refactored the preexisting endpoint used by Tradeview to also return the aggregated results based on a boolean parameter. This would have required more time to make sure I don't break the preexisting endpoint so I left a couple of TODO comments for future improvement.

## Testing

### Steps

1. Do this
2. Then do that

### Expectations

- This
- That

## Links

**Design:** [trade component](https://xd.adobe.com/view/7e4cebbc-a0ce-44c7-9383-789739ce3bea-2b1f/screen/3a6ad1ac-5f40-4f0f-b76e-4fab0f065ac7/specs/)

**Codebase:** [Ticket 81](https://unep-wcmc.codebasehq.com/projects/sustainability-assessment-tool/tickets/81)

## Checklist

- [ ] Tested feature in browser (inc. at different widths if responsive)
- [ ] Linted files
- [ ] Run/passed automated tests (where applicable)
- [ ] Removed any debugger or logging lines
- [ ] Resolved merge conflicts
- [ ] Updated Codebase

2022-06-30 11:11 UTC, yndajas commented
Had an error trying to unzip the expectations downloads, but it turns out they're just single JSON files, so deleting the .zip extension fixes them

2022-06-30 11:39 UTC, lucacug commented
> Had an error trying to unzip the expectations downloads, but it turns out they're just single JSON files, so deleting the .zip extension fixes them

yeah I had to zip them because it didn't like the json format

2022-06-30 11:44 UTC, yndajas requested changes
Haven't tested, but just a few quick comments from browsing the code

2022-08-01 11:33 UTC, yndajas commented
Works good on staging, so I think this can be merged after addressing (or ignoring!) the two comments from https://github.com/unepwcmc/SAPI/pull/862#pullrequestreview-1024693565

2022-08-11 11:08 UTC, merged