Add model and associations for captivity process
unepwcmc/SAPI pull request #881
Opened 2022-09-22 15:51 UTC by roshan-mathewtech

[Ticket#137](https://unep-wcmc.codebasehq.com/projects/cites-support-maintenance/tickets/137)

2022-09-27 19:53 UTC, lucacug requested changes
left few comments, let me know if anything is unclear

2022-09-27 19:53 UTC, lucacug commented on app/models/captivity_process.rb
> +  belongs_to :start_event, :class_name => 'Event'
can we add the `has_many` part of the association on the Event model, please?

2022-09-27 19:53 UTC, lucacug commented on app/models/captivity_process.rb
> +  # enum status: [:ongoing, :trade_suspension, :closed]
As discussed, can we just use a string here and leave a comment that as soon as we upgrade to Rails 4.1 this will be changed to enum type, please?
Can we also validates the value of this field is one of the three expected?

2022-09-27 19:53 UTC, lucacug commented on db/migrate/20220922143605_create_captivity_processes.rb
>        t.integer :status
As discussed, can we just use a string here and leave a comment that as soon as we upgrade to Rails 4.1 this will be changed to enum type, please?

2022-09-27 19:53 UTC, lucacug commented on app/models/captivity_process.rb
>  end
Can we rename this model to `CitesCaptivityProcess` please?

2022-09-27 19:53 UTC, lucacug commented on db/migrate/20220922143605_create_captivity_processes.rb
>      create_table :captivity_processes do |t|
Can we rename this table to `cites_captivity_processes` please?

2022-09-27 19:53 UTC, lucacug commented on app/models/captivity_process.rb
>    validates :geo_entity, presence: true
can we also validate the presence of the `status`, `resolution` and  `start_date`, please?

2022-09-27 19:53 UTC, lucacug commented on app/models/captivity_process.rb
> +  belongs_to :start_event, :class_name => 'Event'
given only 2 types of events will be applicable here, can we validate the values is either one or the other (`CitesAc` and `CitesPc`)?

2022-09-28 10:40 UTC, roshan-mathewtech commented on db/migrate/20220922143605_create_captivity_processes.rb
>      create_table :captivity_processes do |t|
Done

2022-09-28 10:40 UTC, roshan-mathewtech commented on app/models/captivity_process.rb
>  end
Done

2022-09-28 10:41 UTC, roshan-mathewtech commented on db/migrate/20220922143605_create_captivity_processes.rb
>        t.integer :status
Done

2022-09-28 10:41 UTC, roshan-mathewtech commented on app/models/captivity_process.rb
> +  # enum status: [:ongoing, :trade_suspension, :closed]
Done

2022-09-28 10:41 UTC, roshan-mathewtech commented on app/models/captivity_process.rb
> +  belongs_to :start_event, :class_name => 'Event'
Done

2022-09-28 10:41 UTC, roshan-mathewtech commented on app/models/captivity_process.rb
>    validates :geo_entity, presence: true
Done

2022-09-28 10:51 UTC, roshan-mathewtech commented on app/models/captivity_process.rb
> +  belongs_to :start_event, :class_name => 'Event'
The values comes from another table _events_ and _events_ have many records with type as 'CitesAc' and 'CitesPc'
Slightly tricky to do the validation.

2022-09-29 22:09 UTC, lucacug requested changes

2022-09-30 09:16 UTC, roshan-mathewtech commented on app/models/cites_captivity_process.rb
> +    end
This is perfect. 
Done.

2022-10-07 15:50 UTC, merged