Cites process admin UI
unepwcmc/SAPI pull request #885
Opened 2022-09-30 14:32 UTC by roshan-mathewtech

2022-10-03 21:20 UTC, lucacug requested changes
Left a few comments and there is also a file committed  here that is not relevant to this task (data/cms.json, I think this is the API dump for the mobile app) and needs to be removed. Any doubt please let me know

2022-10-03 21:20 UTC, lucacug commented on app/views/admin/cites_captivity_processes/_current_opinions_form.html.erb
> +        <td><%= opinion.internal_notes %></td>
this whole file seems a leftover from a copy and paste, which doesn't make sense here. If you want to keep it, it would need to be adapted to the new entity `CitesCaptivityProcess` while at the moment is still referring to the `EuOpinion`

2022-10-03 21:20 UTC, lucacug commented on app/views/admin/cites_captivity_processes/_form.html.erb
> +<%= admin_new_modal({:title => "Current "}) { render "current_opinions_form" } %>
still a reference to opinions here, can we rename it properly or remove this line please?

2022-10-03 21:20 UTC, lucacug commented on app/controllers/admin/cites_captivity_processes_controller.rb
> +    @meetings = Event.where("type IN ('CitesAc','CitesPc')"
can we rename this to events for consistency, please?

2022-10-03 21:20 UTC, lucacug commented on app/views/admin/cites_captivity_processes/_form.html.erb
> +        options_from_collection_for_select(@meetings, :id, :name, @cites_captivity_process.start_event_id),
can we rename this to events for consistency, please?

2022-10-03 21:20 UTC, lucacug commented on app/views/admin/cites_captivity_processes/_form.html.erb
> +        { :include_blank => true },
I'm thinking, could we remove this for all the mandatory fields? In this case, the form will already show some default values rather than blank and avoid too many errors popping up on the page

2022-10-03 21:20 UTC, lucacug commented on app/views/admin/cites_captivity_processes/_list.html.erb
> +        <%= tracking_info(opinion) %>
loads of reference to opinion, can we rename this properly, please?

2022-10-03 21:20 UTC, lucacug commented on spec/helpers/admin/cites_captivity_processes_helper_spec.rb
> +end
this can be removed given my previous comment

2022-10-04 17:52 UTC, roshan-mathewtech commented on spec/helpers/admin/cites_captivity_processes_helper_spec.rb
> +end
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/views/admin/cites_captivity_processes/_list.html.erb
> +        <%= tracking_info(opinion) %>
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/views/admin/cites_captivity_processes/_form.html.erb
> +        { :include_blank => true },
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/views/admin/cites_captivity_processes/_form.html.erb
> +        options_from_collection_for_select(@meetings, :id, :name, @cites_captivity_process.start_event_id),
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/controllers/admin/cites_captivity_processes_controller.rb
> +    @meetings = Event.where("type IN ('CitesAc','CitesPc')"
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/views/admin/cites_captivity_processes/_form.html.erb
> +<%= admin_new_modal({:title => "Current "}) { render "current_opinions_form" } %>
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/views/admin/cites_captivity_processes/_current_opinions_form.html.erb
> +        <td><%= opinion.internal_notes %></td>
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/models/cites_captivity_process.rb
> +    start_date ? start_date.strftime("%d/%m/%Y") : ""
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/helpers/admin/cites_captivity_processes_helper.rb
> +end
Done

2022-10-04 17:52 UTC, roshan-mathewtech commented on app/controllers/admin/cites_captivity_processes_controller.rb
> +    @purposes = Purpose.order(:code)
Done

2022-10-04 22:48 UTC, lucacug commented
thanks for addressing my comments @roshan-mathewtech  looks good now, the only thing is that it is still present that data/cms.json file. Once you removed it, I'm happy for this to be merged

2022-10-05 22:06 UTC, merged