fix: add term code to data and fix term capitalisation
unepwcmc/SAPI pull request #892
Opened 2022-10-12 14:05 UTC by WillKocur

This adds the term code to trade_over_time endpoint, so that the code can be shown in the frontend of SAT in the legend items.

Also I think fixes the issue of the first letter of the terms not being capitalised.

Linked PR: https://github.com/unepwcmc/sustainability-assessment-tool/pull/56

Note, TradeView uses this too. However this shouldn't cause any problems as TradeView will just ignore the additional code attribute (although, TV is currently doing a little workaround to access the term code (by looking back at the filters in the frontend and finding the code their), so it would be nice at some point to get rid of that workaround and access the code directly with this adjustment.)

2022-10-18 15:17 UTC, lucacug requested changes
A couple of comments here; I haven't checked for an alternative solution, but adding the term codes like this is affecting Tradeview. 
It might need some work on the TdV side of things to fix it leaving the implementation as it is here

2022-10-18 16:04 UTC, WillKocur commented on lib/modules/trade/grouping/trade_plus_static.rb
> +      attribute = "INITCAP(#{attribute})" if attribute == 'term_en'
Ah of course... I can put the frontend fix back in that just capitalises there if that's preferred for now. What do you think?

2022-10-18 16:04 UTC, WillKocur commented on lib/modules/trade/grouping/trade_plus_static.rb
> +      terms: ["term_#{@locale}", 'term_id', 'term_code'],
@lucacug Oh good spot, I didn't expect this! Sorry, should have checked. Will fix TdV side I reckon as tradeview is currently doing this in a roundabout way anyway, so should be able to simplify it there a little 👍

2022-10-18 20:21 UTC, lucacug commented on lib/modules/trade/grouping/trade_plus_static.rb
> +      attribute = "INITCAP(#{attribute})" if attribute == 'term_en'
I think is better to have this logic here in the BE

2022-10-19 07:34 UTC, WillKocur commented on lib/modules/trade/grouping/trade_plus_static.rb
> +      terms: ["term_#{@locale}", 'term_id', 'term_code'],
@lucacug TdV PR here - will add to ticket too. https://github.com/unepwcmc/tradeplus/pull/93

2022-10-19 10:33 UTC, lucacug commented
looks good, merging!

2022-10-19 10:33 UTC, merged