EU accession exit date import task
unepwcmc/SAPI pull request #893
Opened 2022-10-12 15:00 UTC by roshan-mathewtech

[148](https://unep-wcmc.codebasehq.com/projects/cites-support-maintenance/tickets/148)

Create a rake task to import EU accession and exit dates from the CSV file

To import the data to the _eu_country_statuses_ table
Put the **CITES_trade_EU_countries_list.csv** file attached in the above codebase ticket to _lib/files_ and run the below command

```rake import:eu_country_statuses```

2022-10-12 21:51 UTC, lucacug requested changes

2022-10-12 21:51 UTC, lucacug commented on lib/files/CITES_trade_EU_countries_list.csv
> +ISO2,Name_EN,Name_ES,Name_FR,EU_accession,EU_accession_year,EU_exit,EU_exit_year
I would only keep the ISO2, EU_accession_year and EU_exit_year and remove all the other columns from the file, as we don't really need those

2022-10-12 21:51 UTC, lucacug commented on lib/tasks/import_eu_country_statuses.rake
> +	  end
can we fix the indentation here, please?

2022-10-12 21:51 UTC, lucacug commented on lib/tasks/import_eu_country_statuses.rake
> +      csv = CSV.read(file_path, headers: true)
you can use `foreach` rather than `read` to parse the csv, so that you don't need to store all the data into a variable first and iterate after

2022-10-12 21:51 UTC, lucacug commented on lib/tasks/import_eu_country_statuses.rake
> +	    geo_entity = GeoEntity.find_by_iso_code2(row[0])
can we use the column name rather than the column position here, please?  This is more consistent and doesn't require the columns to be in a specific order

2022-10-12 21:51 UTC, lucacug commented on lib/tasks/import_eu_country_statuses.rake
> +	    exit_year = row[7]
same as above

2022-10-12 21:51 UTC, lucacug commented on lib/tasks/import_eu_country_statuses.rake
> +	      end
I would have written this a bit differently, maybe just using a `find_or_initialize_by` method to save some lines of code and make the code more readable. Let' s have a chat tomorrow

2022-10-13 15:31 UTC, roshan-mathewtech commented
Review changes are done

2022-10-13 22:08 UTC, lucacug requested changes

2022-10-13 22:08 UTC, lucacug commented on lib/tasks/import_eu_country_dates.rake
> +  desc 'Import EU country entry/exit dates from csv file usage: rake import:eu_country_statuses'
it should be `import:eu_country_dates` now

2022-10-13 22:08 UTC, lucacug commented on lib/tasks/import_eu_country_dates.rake
> +	  end
can we fix the indentation, please? you must have some auto-formatting during the commit, weird.

2022-10-13 22:08 UTC, lucacug commented on lib/tasks/import_eu_country_dates.rake
> +	    unless geo_entity.nil?
it would be good to have a log of the failed geoentity:
```
if  geo_entity.nil?
  Rails.logger.info 'Country #{row[ISO2]} not found in the DB, skipping...'
  next
end

2022-10-13 22:08 UTC, lucacug commented on lib/tasks/import_eu_country_dates.rake
> +	      geo_entity.eu_country_dates.find_or_create_by(eu_accession_year: accession_year, eu_exit_year: exit_year)
I would not make a join query here, I think we can directly create the EuCountryDate record with:

```
EuCountryDate.find_or_create_by(geo_entity: geo_enitity, eu_accession_year: accession_year, eu_exit_year: exit_year)

2022-10-14 11:03 UTC, roshan-mathewtech commented
Done. Thanks

2022-10-14 15:17 UTC, merged