Create table to store EU entry and exit dates
unepwcmc/SAPI pull request #894
Opened 2022-10-12 15:02 UTC by roshan-mathewtech

[146](https://unep-wcmc.codebasehq.com/projects/cites-support-maintenance/tickets/146)

2022-10-12 21:01 UTC, lucacug requested changes

2022-10-12 21:01 UTC, lucacug commented on db/migrate/20221011142831_create_eu_country_statuses.rb
> +class CreateEuCountryStatuses < ActiveRecord::Migration
I'm not totally convinced by the name of this table, I would have gone with something like `eu_country_dates` maybe? let's have a chat about it

2022-10-13 14:20 UTC, roshan-mathewtech commented
Changes are done. Thanks

2022-10-13 22:22 UTC, lucacug requested changes

2022-10-13 22:22 UTC, lucacug commented on app/models/eu_country_date.rb
> +  def is_country
this doesn't seem to be used anywhere here, we might need to add a `validate` line

2022-10-14 10:46 UTC, roshan-mathewtech commented on app/models/eu_country_date.rb
> +  def is_country
oops!! forgot to add it. Added it now
Thanks

2022-10-14 12:16 UTC, lucacug commented
looks good now! Tagging as don't merge to use it as the feature branch of all this task

2022-10-17 08:42 UTC, lucacug approved these changes

2022-11-10 22:07 UTC, lucacug commented
closing because superseded by this one #904

2022-11-10 22:07 UTC, closed without merging